### ISSUE TITLE
Plugin must be updated to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [JOSM/ShapeTools#3]
See https://josm.openstreetmap.de/ticket/13285

We now use Java 8 predicates instead of custom ones, the plugin must be updated to use OsmPrimitive::isUsable.

See https://josm.openstreetmap.de/changeset/10716/josm/ for details

**Comment by don-vip** [comment]
We have released new tested version, can you please update the plugin? See also https://josm.openstreetmap.de/ticket/13044

**Comment by don-vip** [comment]
We have a lot of users complaining, can you please update soon?

**Comment by simon04** [comment]
Recompiling the plugin should resolve this issue. We, @josm, could perform this step and alter the URL in https://josm.openstreetmap.de/wiki/PluginsSource accordingly.

**Comment by don-vip** [comment]
Adrian, would you be OK to transfer your three JOSM plugins repostories to the @JOSM organization? You would still be maintainer, but at least we could update the plugins ourselves when it is required after a core API modification.

**Comment by don-vip** [comment]
@asrianCron can we please have an answer? We're still facing many bug reports and we must take action.

**Comment by asrianCron** [comment]
Yes, it is ok to transfer the plugins to the JOSM organization. I don't
have enough time right now to maintain them. Do what you want with the code
/ plugins. Do you need me to do something in order for this transfer to
take place?

**Comment by don-vip** [comment]
Thanks! I have created three teams (one per plugin) and invited you:
https://github.com/orgs/JOSM/teams/building-generalization
https://github.com/orgs/JOSM/teams/dxf-import
https://github.com/orgs/JOSM/teams/shapetools

You must accept the invitation, then transfer the repositories as described here:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

**Comment by asrianCron** [comment]
Done. Thank you

**Comment by don-vip** [comment]
many thanks! we will now solve this this issue :)
